### ISSUE TITLE
[BUG] `RepositorioComentarios.MarcarComentarioComoUtil()` produce un `InvalidOperationException` de LINQ

### ISSUE THREAD

**Issue by refmv** [Frozen-Burrito/hydrate-servicio-web#24]
**Describe el Problema**
Marcar comentarios como útiles suele funcionar correctamente, pero en ciertas situaciones el resultado HTTP producido es un código `500` y el mensaje de error de la excepción especifica que se intentó acceder a un elemento (o elementos) de una colección con una query LINQ, pero la colección estaba vacía.

**Cómo Reproducirlo**
Pasos para reproducir este error:
1. Iniciar sesión con una cuenta válida.
2. Navegar a la página de comentarios.
3. Intentar marcar un comentario publicado como "útil".
4. El contador de "marcas como útil" no incrementa, observar el error en la consola del navegador.

**Comportamiento Esperado**
Cuando un usuario que no es el autor de un comentario presiona el botón "marcar como útil", la cuenta de marcas de utilidad del comentario debe incrementar en 1, y el comentario debe ser marcado para el usuario.

**Entorno:**
 - OS: Windows 10
 - Navegador: Brave
 - Versión: 1.0.0+1

**Contexto Adicional**
El output de los logs del servicio web es el siguiente: 
```
2022-11-05T05:01:23.665737785Z info: ServicioHydrate.Controladores.ControladorComentarios[0]
2022-11-05T05:01:23.665796877Z       [11/05/2022 05:01:23] PATCH - /api/v1/comentarios/9/util
2022-11-05T05:01:24.210721682Z fail: ServicioHydrate.Controladores.ControladorComentarios[0]
2022-11-05T05:01:24.210799572Z       Error no identificado en PATCH - /api/v1/comentarios/9/util
2022-11-05T05:01:24.210819669Z       System.InvalidOperationException: Sequence contains no elements
2022-11-05T05:01:24.210830868Z          at System.Linq.ThrowHelper.ThrowNoElementsException()
2022-11-05T05:01:24.210839267Z          at ServicioHydrate.Data.RepositorioComentarios.MarcarComentarioComoUtil(Int32 idComentario, Guid idUsuarioActual) in /home/runner/work/hydrate-servicio-web/hydrate-servicio-web/API/Data/RepositorioComentarios.cs:line 471
2022-11-05T05:01:24.210848265Z          at ServicioHydrate.Controladores.ControladorComentarios.MarcarComentarioComoUtil(Int32 idComentario) in /home/runner/work/hydrate-servicio-web/hydrate-servicio-web/API/Controllers/ControladorComentarios.cs:line 582
```

**Comment by refmv** [comment]
El principal problema es el uso del método `First()` para obtener el primer resultado de una query de LINQ. En casos donde no había registros previos, o cuando ningún registro cumplía con los filtros especificados, este método produce un `InvalidOperationException`. 

Se cambió el uso de `First()` a `FirstOrDefault()`, que produce `null` cuando la colección está vacía.
